[build]
  command = "npm install && npm run build"
  publish = "build"

# [[redirects]]
#   from = "/api-65mz3szb1-mikolajs-projects.vercel.app/*"
#   to = "https://api-65mz3szb1-mikolajs-projects.vercel.app/:splat"
#   status = 200


[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://coruscating-dusk-0c8d64.netlify.app"
      Access-Control-Allow-Methods = "GET, POST, PUT, OPTIONS"
      Access-Control-Allow-Headers = "Content-Type, Authorization"